#pragma once
#include "Factorial.hpp"

constexpr long long unsigned g_FactorialLookUp[20]
{
	FACTORIAL(1),
	FACTORIAL(2),
	FACTORIAL(3),
	FACTORIAL(4),
	FACTORIAL(5),
	FACTORIAL(6),
	FACTORIAL(7),
	FACTORIAL(8),
	FACTORIAL(9),
	FACTORIAL(10),
	FACTORIAL(11),
	FACTORIAL(12),
	FACTORIAL(13),
	FACTORIAL(14),
	FACTORIAL(15),
	FACTORIAL(16),
	FACTORIAL(17),
	FACTORIAL(18),
	FACTORIAL(19),
	FACTORIAL(20)
};
